### ISSUE TITLE
optimize the code

### ISSUE THREAD

**Issue by phenix1983** [sthoduka/fmt_motion_detection#2]
Hi, I tried the algorithm run on the Qualcomm 820,  resize image to 320x240,  each frame process time is about   1200ms. too long. do you have faster version? :)

**Comment by phenix1983** [comment]
Especially, the image registration based on FFTW， it's really a big time cost.

**Comment by sthoduka** [comment]
I do not have a faster version. In principle, you can replace the fftw image registration with some other method (for example using libviso2), and still run the motion detection code from this repository. 

How fast does it run on an Intel i3, for example. I've only tested it on a 1.7GHz Intel i3, and the image registration was running at ~14 Hz and image registration + motion detection at 11 Hz. Are you sure that you're building with compiler optimizations enabled?

**Comment by phenix1983** [comment]
yes , -O3  was not open, but if use -neon -O3, which version FFTW should I use? If change FFTW version, the API should be changed? such as "fftw_plan_dft_2d" , "fftw_destroy_plan" and so on.

**Comment by phenix1983** [comment]
You are great, the option -O3 was not opened yesterday. :) after open it, Average time cost is about 300ms per frame,  I want to use neon,
 after change FFTW functions "fftw_xxx" to "fftwf_xxx" in file image_dft.cpp
using the attchment Makefile. the result is in the picture. should I change something for Eigen? Thank you very much in advance.
![image](https://user-images.githubusercontent.com/25242660/35262250-cebc9ce0-004e-11e8-8d1e-ec06f9712cdc.png)

[Makefile.zip](https://github.com/sthoduka/fmt_motion_detection/files/1654868/Makefile.zip)

**Comment by sthoduka** [comment]
everywhere in the code I use double precision numbers. For example, in `imreg_fmt/include/imreg_fmt/image_dft.h`, the `ComplexMatrix` is defined with double type. Also, I use `MatrixXd`, `VectorXd` etc. 

Since you switched to using single precision fftw, it's possible that is what causes the problem. Does it work without problems with fftw (not fftwf)?

Also, what is neon?

**Comment by phenix1983** [comment]
neon means an option '--enable-neon' , assembly instruction set,  https://github.com/hekai/fftw_android/blob/master/README.md 
http://www.vesperix.com/arm/fftw-arm/source/index.html 
I want to get it run faster. :)

**Comment by phenix1983** [comment]
I want to get it run faster, now time cost is about 180ms . Could you give me the Makefile when you run on the Intel paltform? Thanks.

**Comment by phenix1983** [comment]
I want to see the optimize options.

**Comment by phenix1983** [comment]
Now, I use the fftwf_xxx， I want to see optimize options. ：）

**Comment by sthoduka** [comment]
I use cmake, and set `CMAKE_BUILD_TYPE` to Release. I think that just sets `-O3` as you did. I did not use any other options.

**Comment by phenix1983** [comment]
Thank you.:)

**Comment by phenix1983** [comment]
Hi, I want to confirm two problem, 
1. Did you use the same code as the version download from this link, when you run on intel platform? 
2. Have you tried libviso2 to do image registration, is it faster than FFTW3.3.7 ?
 could you tell me the FFTW version you used?

Thank you.

**Comment by sthoduka** [comment]
1. yes I used the same code (I assume you mean the code from this repository)
2. Yes, I tried it with libviso2, it was only marginally faster (12 Hz using libviso2 and 11Hz using fftw for the entire pipeline). 
3. At the time I tested, I was using fftw3.3.4.

**Comment by phenix1983** [comment]
Now, I wan to try openCL ,https://github.com/clMathLibraries/clFFT 
Trying .
