### ISSUE TITLE
Whether is the "percentile" necessary  when doing difference? 

### ISSUE THREAD

**Issue by phenix1983** [sthoduka/fmt_motion_detection#3]
float norm = percentile(im1, 0.90) / percentile(im0, 0.90);

**Comment by sthoduka** [comment]
it is not required, but it seems to make the difference slightly better. It increases the contrast of the difference image. I got the idea from the Python implementation [here](https://github.com/matejak/imreg_dft/blob/master/src/imreg_dft/imreg.py#L704).

**Comment by phenix1983** [comment]
Thank you! ：）
